### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iqnite** [gtrifonov/raspberry-pi-alpine-azure-cli#2]
I tried to install it and this is the response to the command sudo docker exec cli az login:

pi@raspberrypi:~ $ sudo docker exec cli az login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/azure/cli/__main__.py", line 34, in <module>
    az_cli = get_default_cli()
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 599, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 425
    def cached_put(cmd_obj, operation, parameters, *args, setter_arg_name='parameters', **kwargs):
                                                                        ^
SyntaxError: invalid syntax

Why does this happen?

**Comment by iqnite** [comment]
This project is no longer active
